###########################
# Endpoints Configuration #
###########################

mainnet:
  lcd: "http://lcd.axelarscan.io:80" # "http://ec2-18-218-242-252.us-east-2.compute.amazonaws.com:1317"
  lcd_archive: "http://archive-node-lcd.axelarscan.io:80" # "http://ec2-18-218-242-252.us-east-2.compute.amazonaws.com:1317"
  validator_api: "https://ww5e4qrad0.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/validator"
  token_transfer_api: "https://xo550w4a8b.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/token"
  gmp_api: "https://api.axelarscan.io/gmp" # "https://ec2ny1mc5e.execute-api.us-east-2.amazonaws.com"
  app: "https://axelarscan.io"

testnet:
  lcd: "http://testnet.lcd.axelarscan.io:80"
  lcd_archive: "https://axelart.lava.build"
  validator_api: "https://762da1qejd.execute-api.us-east-2.amazonaws.com"
  token_transfer_api: "https://dl5bgfjozd.execute-api.us-east-2.amazonaws.com"
  gmp_api: "https://testnet.api.axelarscan.io/gmp"
  app: "https://testnet.axelarscan.io"

stagenet:
  lcd: "http://stagenet.archive-node-lcd.axelarscan.io:80"
  lcd_archive: "http://stagenet.archive-node-lcd.axelarscan.io:80"
  validator_api: "https://g45hmsa0tg.execute-api.us-east-2.amazonaws.com"
  token_transfer_api: "https://glhbed8wmg.execute-api.us-east-2.amazonaws.com"
  gmp_api: "https://stagenet.api.axelarscan.io/gmp"
  app: "https://stagenet.axelarscan.io"

devnet-amplifier:
  lcd: "http://devnet-amplifier.archive-node-lcd.axelarscan.io:80"
  lcd_archive: "http://devnet-amplifier.archive-node-lcd.axelarscan.io:80"
  validator_api: "https://devnet-amplifier.api.axelarscan.io/validator"
  token_transfer_api: "https://devnet-amplifier.api.axelarscan.io/token"
  gmp_api: "https://devnet-amplifier.api.axelarscan.io/gmp"
  app: "https://devnet-amplifier.axelarscan.io"
