name: Test CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.19.4"]

    services:
      opensearch:
        image: opensearchproject/opensearch:2.11.0
        env:
          cluster.name: axelarscan-api-cluster
          node.name: axelarscan-api-node
          discovery.type: single-node
          bootstrap.memory_lock: true
          "OPENSEARCH_JAVA_OPTS": "-Xms512m -Xmx512m"
          "DISABLE_INSTALL_DEMO_CONFIG": "true"
          "DISABLE_SECURITY_PLUGIN": "true"
        ports:
          - 9200:9200
          - 9600:9600
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 12
          --ulimit nofile=65536:65536
          --ulimit memlock=-1:-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up environment variables
        run: |
          echo "ENVIRONMENT=testnet" >> $GITHUB_ENV
          echo "LOG_LEVEL=debug" >> $GITHUB_ENV
          echo "NODE_NO_WARNINGS=1" >> $GITHUB_ENV
          echo "INDEXER_URL=http://localhost:9200" >> $GITHUB_ENV
          echo "DD_TRACE_ENABLED=false" >> $GITHUB_ENV
          echo "DD_ENHANCED_METRICS=false" >> $GITHUB_ENV

      - name: Run linting check (non-blocking)
        run: |
          echo "Running ESLint..."
          pnpm run lint:check || echo "Linting failed but continuing..."
          echo "Linting completed"

      - name: Run formatting check
        run: |
          echo "Running Prettier format check..."
          pnpm run format:check
          echo "Format check completed"
